# Generated by Django 4.0 on 2022-01-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='articles',
            name='time_create',
            field=models.DateTimeField(null=True, verbose_name='Время создания'),
        ),
    ]
