# Generated by Django 4.0 on 2022-01-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_articles_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='time_create',
            field=models.TimeField(null=True, verbose_name='Время создания'),
        ),
    ]
